export const chapterName = ["Real_Number","Polynomials","Pair_of_Linear_Equations_in_two_variables",
"Quardatic_Equations","Arithmetic_Progression","Triangles","Coordinate_Geometry","Introduction_to_Trignometry",
"Some_applications_of_Trigonometry","Circles","Constructions","Area_related_to_Circles","Surface_areas_and_volumes","Statistics","Probability"]
export const givenTopics= ["Euclid's division algorithm","The fundamental theorem of arithmetic",
"Degrees of polynomia",
	"Geometrical meaning of the zeroes",
	"Plotting of equations",
	"The relationship between zeroes and coefficients of a polynomial",
	"Sum and product of zeroes",
	"Division algorithms for polynomials",

    "Graphical Method of Solution of a Pair of Linear Equations",
	"Algebraic Methods of Solving a Pair of Linear Equations",
	"Equations Reducible to a Pair of Linear Equations in Two Variables",

    "Factorisation",
	"Completing the Squares",
	"Quadratic formula",

"Basic concept of arithmetic progression",
	"Sum of First n Terms of an AP",
    "Properties of triangle",
	"Similarity of Triangles",
	"Basic proportionality theorem and its converse",
	"Areas of similar triangles",
	"Pythagoras theorem",
    "Distance between the two points",
	"Find the area of the triangles formed by three given points",
	"Distance formula",
	"Section formula",
	"Mid-point of the line segment",
    "Trigonometric ratios of the angles",
	"Trigonometric ratios of complementary angles",
	"Trigonometric identities",
    "Height and Distances",
	"Distance between two objects",
    "Tangent to a Circle",
	"Number of tangents from a point on a circle",
    "To divide a line segment in the given ratio",
	"To construct a triangle similar to the given triangle as per the given scale factor",
    "To construct the pair of tangents from an external point to a circle",
    "Perimeter and area of a circle",
"Areas of sector and segment of a circle",
"Areas of combination of plane figures",

    "Surface areas and volumes of combination of solids",
	"Conversion of solid from one shape to another",
	"Frustum of a cone",
	"Slant height, curved surface area, total surface area and volume of the frustum of a c",
    "Cumulative frequency",
	"Frequency distribution (cumulative)",
	"Cumulative frequency curves (ogives)",
	"Mean of Grouped Data",
	"Mode of grouped data",
	"Median of Grouped Data",
	"Graphical Representation of Cumulative Frequency Distribution",
    "Probability- A Theoretical Approach",
	"Complementary event",
]
